### ISSUE TITLE
Displaying s-expressions doesn't produce valid Ion

### ISSUE THREAD

**Issue by sadderchris** [amzn/ion-rust#403] opened 2022-08-04 23:14 UTC
Using the `OwnedElement` API, if I try to display an s-expression, I get something like this:

```ion
( 1, two, "three" )
```

I would expect this to produce something more like:

```ion
(1 two "three")
```

Looking at the code, it seems like the [s-exp formatter](https://github.com/amzn/ion-rust/blob/593687c061c3b050e7935f211d98f85d8167da10/src/text/text_formatter.rs#L499) is a carbon copy of the [list formatter](https://github.com/amzn/ion-rust/blob/593687c061c3b050e7935f211d98f85d8167da10/src/text/text_formatter.rs#L513), minus the parentheses instead of square brackets.  Is there a good reason for this?  Is the `Display` implementation for `OwnedElement` not meant to produce valid Ion?  It seems odd that everything else there spits out valid Ion, but the s-expression formatter doesn't.

**Comment by zslayton** [comment] 2022-08-08 21:08
This is not the intended behavior, thanks for pointing it out. We'll get this fixed in the next release. CC @desaikd

**Closed** 2022-08-10 18:49 UTC
